### ISSUE TITLE
swarm_detector未启动

### ISSUE THREAD

**Issue by GSKun1** [zidiyang/omni_swarm_docker#3]
这个项目我可以正常启动，但是在运行过程中我发现swarm_detector节点并未正常启动，不知道是否合理，应该怎么解决

此前我已经查看了，所对应的launch应当是启动了这个节点

**Comment by zidiyang** [comment]
这个docker在我的机器上是能够正常启动swarm_detector节点的，对编译swarm_detector的一系列处理也是在容器中进行的，理论上应该与主机差异无关，如果出现节点无法启动的情况，可能是拉取docker容器时因网络而拉取不完整？您可以检查运行过程中输出有无报错信息。
另外，虽然swarm_detector并无问题，但实际上此项目中的swarm_loop在我的测试中是存在问题的，仅在单机内进行了loop，但是为了不对使用者产生误导，我保持了完全的原始omni-swarm代码，并未进行debug，不知道是否是您疑问的方面。

**Comment by GSKun1** [comment]
谢谢您的及时回复，我仔细查看了在运行时终端的输出，发现
![image](https://github.com/user-attachments/assets/2b06cc09-13ae-4d6a-afaa-75cd9a419fb9)
确实swarm_detector这个节点未能成功启动

但在此之前，我并未修改或是重新编译docker中的image或是容器中的任何文件

**Comment by GSKun1** [comment]
我在容器中单独运行detector.launch

... logging to /root/.ros/log/1a42fb24-be01-11ef-907a-0242ac110003/roslaunch-2bb494feff6f-29313.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://2bb494feff6f:44549/

SUMMARY
========

PARAMETERS
 * /SwarmDetector/acpt_overlap_thres: 5
 * /SwarmDetector/cam_file: /root/swarm_ws/sr...
 * /SwarmDetector/cam_file_down: /root/swarm_ws/sr...
 * /SwarmDetector/darknet_cfg: /root/swarm_ws/sr...
 * /SwarmDetector/debug_only_front: False
 * /SwarmDetector/debug_save_tracked_raw: False
 * /SwarmDetector/detect_duration: 1.0
 * /SwarmDetector/down_as_main: False
 * /SwarmDetector/drone_id: 1
 * /SwarmDetector/drone_pose_height: 128
 * /SwarmDetector/drone_pose_network_model: /root/swarm_ws/sr...
 * /SwarmDetector/drone_pose_width: 128
 * /SwarmDetector/drone_pose_zoom: 4
 * /SwarmDetector/drone_scale: 0.48
 * /SwarmDetector/enable_down_cam: True
 * /SwarmDetector/enable_rear: False
 * /SwarmDetector/enable_tracker: True
 * /SwarmDetector/enable_triangulation: False
 * /SwarmDetector/enable_up_cam: True
 * /SwarmDetector/extrinsic_path: /home/dji/SwarmCo...
 * /SwarmDetector/fov: 235
 * /SwarmDetector/gamma: 0.6
 * /SwarmDetector/min_p: 0.1
 * /SwarmDetector/overlap_thres: 0.1
 * /SwarmDetector/p_track: 0.999
 * /SwarmDetector/pub_anonymous: True
 * /SwarmDetector/pub_image: False
 * /SwarmDetector/pub_track_result: False
 * /SwarmDetector/show: False
 * /SwarmDetector/show_width: 1080
 * /SwarmDetector/tensorrt_fp16: True
 * /SwarmDetector/thres: 0.5
 * /SwarmDetector/triangulation_thres: 0.2
 * /SwarmDetector/use_tensorrt: True
 * /SwarmDetector/weights: /root/swarm_ws/sr...
 * /SwarmDetector/width: 400
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /
    SwarmDetector (nodelet/nodelet)
    detection_manager (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

process[detection_manager-1]: started with pid [29336]
[ INFO] [1734614058.419461814]: Initializing nodelet with 16 worker threads.
process[SwarmDetector-2]: started with pid [29337]
[ INFO] [1734614058.467614394]: Loading nodelet /SwarmDetector of type swarm_detector_pkg/SwarmDetector to manager /detection_manager with the following remappings:
[ INFO] [1734614058.468483997]: /SwarmDetector/image_front -> /flattener/fuck
[ INFO] [1734614058.468497197]: /SwarmDetector/image_raw -> /pg_0/image_raw
[ INFO] [1734614058.468504461]: /SwarmDetector/imu -> /dji_sdk_1/dji_sdk/imu
[ INFO] [1734614058.468514588]: /SwarmDetector/odometry -> /vins_estimator/imu_propagate
[ INFO] [1734614058.468521572]: /SwarmDetector/swarm_fused -> /swarm_drones/swarm_drone_fused
[ INFO] [1734614058.468531560]: /SwarmDetector/vins_flattened -> /vins_estimator/flattened_raw
[ INFO] [1734614058.632456438]: [SWARM_DETECT] Try to read extrinsic from /home/dji/SwarmConfig/fisheye_ptgrey_n3/fisheye_cuda.yaml camera from /root/swarm_ws/src/swarm_detector/config/ptgrey_17591762_camera_calib.yaml
[ WARN] [1734614058.632489822]: [SWARM_DETECT] Config_file dosen't exist; Assume identity camera pose
Translation   0.105
0.004614
  0.0898Loading TRT Engine...
WARNING: Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
ERROR: /_src/rtSafe/resources.h (441) - Cuda Error in loadKernel: 200 (device kernel image is invalid)
ERROR: INVALID_STATE: std::exception
ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Loading Complete!
Stack trace (most recent call last):
#16   Object "", at 0xffffffffffffffff, in 
#15   Object "/opt/ros/melodic/lib/nodelet/nodelet", at 0x55931681d1a9, in _start
#14   Source "../csu/libc-start.c", line 310, in __libc_start_main [0x7f562abebbf6]
#13   Object "/opt/ros/melodic/lib/nodelet/nodelet", at 0x55931681be93, in main
#12   Object "/opt/ros/melodic/lib/libroscpp.so", at 0x7f562c10492a, in ros::spin()
#11   Object "/opt/ros/melodic/lib/libroscpp.so", at 0x7f562c11bfc8, in ros::SingleThreadedSpinner::spin(ros::CallbackQueue*)
#10   Object "/opt/ros/melodic/lib/libroscpp.so", at 0x7f562c0c4b0a, in ros::CallbackQueue::callAvailable(ros::WallDuration)
#9    Object "/opt/ros/melodic/lib/libroscpp.so", at 0x7f562c0c2d98, in ros::CallbackQueue::callOneCB(ros::CallbackQueue::TLS*)
#8    Object "/opt/ros/melodic/lib/libroscpp.so", at 0x7f562c06e8d3, in ros::ServiceCallback::call()
#7    Object "/opt/ros/melodic/lib/libnodeletlib.so", at 0x7f562c7eaf37, in ros::ServiceCallbackHelperT<ros::ServiceSpec<nodelet::NodeletLoadRequest_<std::allocator<void> >, nodelet::NodeletLoadResponse_<std::allocator<void> > > >::call(ros::ServiceCallbackHelperCallParams&)
#6    Object "/opt/ros/melodic/lib/libnodeletlib.so", at 0x7f562c7e309f, in nodelet::LoaderROS::serviceLoad(nodelet::NodeletLoadRequest_<std::allocator<void> >&, nodelet::NodeletLoadResponse_<std::allocator<void> >&)
#5    Object "/opt/ros/melodic/lib/libnodeletlib.so", at 0x7f562c7d509e, in nodelet::Loader::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
#4    Object "/opt/ros/melodic/lib/libnodeletlib.so", at 0x7f562c7d2724, in nodelet::Nodelet::init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, ros::CallbackQueueInterface*, ros::CallbackQueueInterface*)
#3  | Source "/root/swarm_ws/src/swarm_detector/src/swarm_detector.cpp", line 160, in TensorRTDetector
    |   159:     if(use_tensorrt) {
    | > 160:         detector = new TensorRTDetector(darknet_weights_path, darknet_cfg, thres, overlap_thres, tensorrt_fp16);
    |   161:     } else {
    |   162:         detector = new DarknetDetector(darknet_weights_path, darknet_cfg, thres, overlap_thres);
      Source "/root/swarm_ws/src/swarm_detector/include/swarm_detector/tensorrt_detector.hpp", line 23, in onInit [0x7f562022c867]
         20:         }
         21:         config.detect_thresh = _thres;
         22:         config.net_type = YOLOV4_TINY;
      >  23:         detector.init(config);
         24: 
         25:     }
#2    Object "/root/source/yolo-tensorrt/build/libdetector.so", at 0x7f560455c20e, in Detector::init(Config const&)
#1    Object "/root/source/yolo-tensorrt/build/libdetector.so", at 0x7f560458d508, in YoloV4::YoloV4(NetworkInfo const&, InferParams const&)
#0    Object "/root/source/yolo-tensorrt/build/libdetector.so", at 0x7f56045863c8, in Yolo::Yolo(NetworkInfo const&, InferParams const&)
Segmentation fault (Address not mapped to object [(nil)])
[FATAL] [1734614064.960562525]: Failed to load nodelet '/SwarmDetector` of type `swarm_detector_pkg/SwarmDetector` to manager `/detection_manager'
[detection_manager-1] process has died [pid 29336, exit code -11, cmd /opt/ros/melodic/lib/nodelet/nodelet manager --no-bond __name:=detection_manager __log:=/root/.ros/log/1a42fb24-be01-11ef-907a-0242ac110003/detection_manager-1.log].
log file: /root/.ros/log/1a42fb24-be01-11ef-907a-0242ac110003/detection_manager-1*.log
[SwarmDetector-2] process has died [pid 29337, exit code 255, cmd /opt/ros/melodic/lib/nodelet/nodelet load swarm_detector_pkg/SwarmDetector /detection_manager --no-bond ~image_raw:=/pg_0/image_raw ~image_front:=/flattener/fuck ~odometry:=/vins_estimator/imu_propagate ~imu:=/dji_sdk_1/dji_sdk/imu ~vins_flattened:=/vins_estimator/flattened_raw ~swarm_fused:=/swarm_drones/swarm_drone_fused __name:=SwarmDetector __log:=/root/.ros/log/1a42fb24-be01-11ef-907a-0242ac110003/SwarmDetector-2.log].
log file: /root/.ros/log/1a42fb24-be01-11ef-907a-0242ac110003/SwarmDetector-2*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

![image](https://github.com/user-attachments/assets/7a1e3461-9a90-4686-b0cd-9de76d1e5aca)
![image](https://github.com/user-attachments/assets/fdaf364a-3693-44a7-b87f-2eb743c05f45)

**Comment by zidiyang** [comment]
从报错信息来看，应该是docker无法调用你主机的显卡，因此无法通过cuda调动GPU以运行detector，对此你可以检查以下几个方面：1. 主机是否安装显卡驱动； 2. 通过命令 docker run  --gpus all  -it blueberryfaygo/compiled_omniswarm:pc 启动docker，然后通过命令nvidia-smi查看是否正常输出（其中 --gpus参数使docker接入你的显卡，在sync_bag_player的脚本docker_swarm_test.py中同样是通过这种方式启动容器）
你可以参考这篇博客：https://www.cnblogs.com/chester-cs/p/14444247.html

**Comment by GSKun1** [comment]
上述的错误跟您在博客中在非docker中配置环境中提到的有些相似，但是在docker中trt版本是7，您提到的解决方案不适配

我尝试转换，并修改detector.launch中对应的模型，仍然失败，报错信息与之前一致

**Comment by GSKun1** [comment]
感谢您在这么晚回复我，

首先我的容器是通过docker_swarm_test.py启动的

我在宿主机和docker容器中分别查看了，均安装了显卡驱动的

![image](https://github.com/user-attachments/assets/d56906cb-4039-42f1-9aeb-85c2af80bf27)

是我的GPU是3070的原因吗

**Comment by zidiyang** [comment]
你安装的是否是nvidia-docker？ https://blog.csdn.net/qq_41776453/article/details/129794608

**Comment by GSKun1** [comment]
![image](https://github.com/user-attachments/assets/3192bcc9-71fe-4ca9-bbf8-a94a27f1b3a4)
是的

**Comment by zidiyang** [comment]
来自GPT：报错可能原因：
· TensorRT 引擎文件可能是为不同的 GPU 架构编译的，而你当前使用的 GPU 可能与引擎文件不兼容（例如，针对不同的 CUDA 架构编译的模型）。
· CUDA 运行时环境或驱动版本不兼容。
· 你使用的 TensorRT 引擎文件可能损坏，或者没有正确构建。

从你的输出来看，你的显卡驱动版本是470，而docker中的cuda版本通过nvcc -V查看为11.1，理论上cuda版本与你的驱动应该是兼容的，那么你可以重点检查TensorRT与你的环境是否适配的问题，比如重新下载swarm_detector的config中的模型并替换docker中的，或是检查TensorRT版本与你的显卡驱动是否兼容。

我仅能将我的输出以及显卡驱动信息给你参考：
[ INFO] [1734656687.853928809]: Loading nodelet /SwarmDetector of type swarm_detector_pkg/SwarmDetector to manager /detection_manager with the following remappings:
[ INFO] [1734656687.854646219]: /SwarmDetector/image_front -> /flattener/fuck
[ INFO] [1734656687.854663463]: /SwarmDetector/image_raw -> /pg_0/image_raw
[ INFO] [1734656687.854673866]: /SwarmDetector/imu -> /dji_sdk_1/dji_sdk/imu
[ INFO] [1734656687.854684826]: /SwarmDetector/odometry -> /vins_estimator/imu_propagate
[ INFO] [1734656687.854693483]: /SwarmDetector/swarm_fused -> /swarm_drones/swarm_drone_fused
[ INFO] [1734656687.854703537]: /SwarmDetector/vins_flattened -> /vins_estimator/flattened_raw
[ INFO] [1734656688.425207702]: [SWARM_DETECT] Try to read extrinsic from /home/dji/SwarmConfig/fisheye_ptgrey_n3/fisheye_cuda.yaml camera from /root/swarm_ws/src/swarm_detector/config/ptgrey_17591762_camera_calib.yaml
[ WARN] [1734656688.425239607]: [SWARM_DETECT] Config_file dosen't exist; Assume identity camera pose
Translation   0.105
0.004614
  0.0898Loading TRT Engine...
Loading Complete!
Width: 32 Height: 32 Zoom: 4
Trying to init TRT engine of DronePoseNetwork/root/swarm_ws/src/swarm_detector/config/drone_pose_v1_128x128_rtx3080_fp16.trt
Loading TRT Engine...
WARNING: Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
Loading Complete!
TensorRT binding index 0 name image
TensorRT binding index 1 name heatmap
MaxBatchSize32
Tensorheatmap bind to 1 dim 1 11 32 32
TensorRT workspace 0mb
[ INFO] [1734656699.075972311]: Center FOV: 2.181662_center
[ INFO] [1734656699.076592819]: Side image height: 208
[ INFO] [1734656699.112962624]: undismap size 5
[ INFO] [1734656699.133338503]: Center FOV: 2.181662_center
[ INFO] [1734656699.133369081]: Side image height: 208
[ INFO] [1734656699.163636155]: undismap size 5
[ INFO] [1734656699.164983358]: [SWARM_DETECT] Init tracker on 0 with P 0.105000 0.004614 0.089800 R
1 0 0
0 1 0
0 0 1
[ INFO] [1734656699.165064342]: [SWARM_DETECT] Init tracker on 1 with P 0.105000 0.004614 0.089800 R
          1           0           0
          0 2.22045e-16           1
          0          -1 2.22045e-16
[ INFO] [1734656699.165122149]: [SWARM_DETECT] Init tracker on 2 with P 0.105000 0.004614 0.089800 R
 2.22045e-16            0            1
          -1  2.22045e-16  2.22045e-16
-2.22045e-16           -1            0
[ INFO] [1734656699.165182328]: [SWARM_DETECT] Init tracker on 3 with P 0.105000 0.004614 0.089800 R
          -1 -2.46519e-32  3.14018e-16
-3.14018e-16  2.22045e-16           -1
-2.46519e-32           -1 -2.22045e-16
[ INFO] [1734656699.165235108]: [SWARM_DETECT] Init tracker on 4 with P 0.105000 0.004614 0.089800 R
-6.66134e-16            0           -1
           1  1.11022e-16 -5.55112e-16
 1.66533e-16           -1            0
[ INFO] [1734656699.172325360]: [SWARM_DETECT] Finish initialize swarm detector, wait for data


root@79a90e38cdf7:~/swarm_ws# nvidia-smi
Fri Dec 20 09:11:15 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3070 ...    Off | 00000000:01:00.0  On |                  N/A |
| N/A   49C    P8              21W / 115W |   1540MiB /  8192MiB |     61%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+

**Comment by zidiyang** [comment]
来自GPT：报错可能原因：
· TensorRT 引擎文件可能是为不同的 GPU 架构编译的，而你当前使用的 GPU 可能与引擎文件不兼容（例如，针对不同的 CUDA 架构编译的模型）。
· CUDA 运行时环境或驱动版本不兼容。
· 你使用的 TensorRT 引擎文件可能损坏，或者没有正确构建。

从你的输出来看，你的显卡驱动版本是470，而docker中的cuda版本通过nvcc -V查看为11.1，理论上cuda版本与你的驱动应该是兼容的，那么你可以重点检查TensorRT与你的环境是否适配的问题，比如重新下载swarm_detector的config中的模型并替换docker中的，或是检查TensorRT版本与你的显卡驱动是否兼容。

我仅能将我的输出以及显卡驱动信息给你参考：
[ INFO] [1734656687.853928809]: Loading nodelet /SwarmDetector of type swarm_detector_pkg/SwarmDetector to manager /detection_manager with the following remappings:
[ INFO] [1734656687.854646219]: /SwarmDetector/image_front -> /flattener/fuck
[ INFO] [1734656687.854663463]: /SwarmDetector/image_raw -> /pg_0/image_raw
[ INFO] [1734656687.854673866]: /SwarmDetector/imu -> /dji_sdk_1/dji_sdk/imu
[ INFO] [1734656687.854684826]: /SwarmDetector/odometry -> /vins_estimator/imu_propagate
[ INFO] [1734656687.854693483]: /SwarmDetector/swarm_fused -> /swarm_drones/swarm_drone_fused
[ INFO] [1734656687.854703537]: /SwarmDetector/vins_flattened -> /vins_estimator/flattened_raw
[ INFO] [1734656688.425207702]: [SWARM_DETECT] Try to read extrinsic from /home/dji/SwarmConfig/fisheye_ptgrey_n3/fisheye_cuda.yaml camera from /root/swarm_ws/src/swarm_detector/config/ptgrey_17591762_camera_calib.yaml
[ WARN] [1734656688.425239607]: [SWARM_DETECT] Config_file dosen't exist; Assume identity camera pose
Translation   0.105
0.004614
  0.0898Loading TRT Engine...
Loading Complete!
Width: 32 Height: 32 Zoom: 4
Trying to init TRT engine of DronePoseNetwork/root/swarm_ws/src/swarm_detector/config/drone_pose_v1_128x128_rtx3080_fp16.trt
Loading TRT Engine...
WARNING: Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
Loading Complete!
TensorRT binding index 0 name image
TensorRT binding index 1 name heatmap
MaxBatchSize32
Tensorheatmap bind to 1 dim 1 11 32 32
TensorRT workspace 0mb
[ INFO] [1734656699.075972311]: Center FOV: 2.181662_center
[ INFO] [1734656699.076592819]: Side image height: 208
[ INFO] [1734656699.112962624]: undismap size 5
[ INFO] [1734656699.133338503]: Center FOV: 2.181662_center
[ INFO] [1734656699.133369081]: Side image height: 208
[ INFO] [1734656699.163636155]: undismap size 5
[ INFO] [1734656699.164983358]: [SWARM_DETECT] Init tracker on 0 with P 0.105000 0.004614 0.089800 R
1 0 0
0 1 0
0 0 1
[ INFO] [1734656699.165064342]: [SWARM_DETECT] Init tracker on 1 with P 0.105000 0.004614 0.089800 R
          1           0           0
          0 2.22045e-16           1
          0          -1 2.22045e-16
[ INFO] [1734656699.165122149]: [SWARM_DETECT] Init tracker on 2 with P 0.105000 0.004614 0.089800 R
 2.22045e-16            0            1
          -1  2.22045e-16  2.22045e-16
-2.22045e-16           -1            0
[ INFO] [1734656699.165182328]: [SWARM_DETECT] Init tracker on 3 with P 0.105000 0.004614 0.089800 R
          -1 -2.46519e-32  3.14018e-16
-3.14018e-16  2.22045e-16           -1
-2.46519e-32           -1 -2.22045e-16
[ INFO] [1734656699.165235108]: [SWARM_DETECT] Init tracker on 4 with P 0.105000 0.004614 0.089800 R
-6.66134e-16            0           -1
           1  1.11022e-16 -5.55112e-16
 1.66533e-16           -1            0
[ INFO] [1734656699.172325360]: [SWARM_DETECT] Finish initialize swarm detector, wait for data


root@79a90e38cdf7:~/swarm_ws# nvidia-smi
Fri Dec 20 09:11:15 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3070 ...    Off | 00000000:01:00.0  On |                  N/A |
| N/A   49C    P8              21W / 115W |   1540MiB /  8192MiB |     61%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+

**Comment by GSKun1** [comment]
这应该确实是由于TensorRT引起的，在代码中我将其禁用，使用Darknet之后，该节点可以正常启动，但是该节点所涉及到的话题消息未能如期发布，例如/swarm_detection/swarm_detected_raw   、/swarm_drones/node_detected_6d

您方便的话，能否打印一下rqt中的节点图和上述两个消息的输出（不确定是否是由于数据集，无人机检测失败造成的原因，故想验证一下）

十分感谢
![rosgraph_stop_trt](https://github.com/user-attachments/assets/e4051452-3298-4dec-9259-b8a909a2f767)

十分感谢

**Comment by zidiyang** [comment]
1. 话题/swarm_detection/swarm_detected_raw输出：
```
header: 
  seq: 62
  stamp: 
    secs: 1637046834
    nsecs: 638889551
  frame_id: ''
self_drone_id: 1
detected_nodes: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1637046834
        nsecs: 638889551
      frame_id: ''
    id: 1000099
    self_drone_id: 1
    remote_drone_id: 1014
    relative_pose: 
      pose: 
        position: 
          x: 0.818925762594
          y: 3.61638585619
          z: 0.899746185679
        orientation: 
          x: -0.0
          y: -0.0
          z: -0.0395660818116
          w: 0.999216956006
      covariance: [6.901705006999199, 29.36776708215695, 6.04026669063359, 0.017396014693181347, 1.9823963349969362, 0.07733864524480547, 29.36776708215695, 126.18754171592543, 25.932971622383324, -0.03190352940521057, 8.673842609185337, 1.125847672968531, 6.040266690633591, 25.932971622383327, 5.387045904993505, -0.004387872583206727, 1.7893724705473524, 0.17170589020975188, 0.01739601469318132, -0.03190352940521063, -0.004387872583206748, 0.06699707262146154, 0.06654931712388847, -0.39323229645674634, 1.9823963349969351, 8.673842609185334, 1.789372470547352, 0.06654931712388848, 1.6440103222307318, -0.22998427836600538, 0.07733864524480558, 1.125847672968531, 0.17170589020975197, -0.39323229645674634, -0.22998427836600527, 2.6800994171830066]
    is_2d_detect: False
    is_yaw_valid: True
    probaility: 0.712159633636
    local_pose_self: 
      position: 
        x: -1.17251996121
        y: -0.927292141162
        z: 1.00749312549
      orientation: 
        x: -0.00118129977385
        y: 0.0265279274851
        z: 0.273077533245
        w: 0.961625464737
    local_pose_remote: 
      position: 
        x: 0.0
        y: 0.0
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 0.0
    dof_4: True
detected_nodes_xyz_yaw: []
is_6d_detect: False

```
2. 话题/swarm_drones/node_detected_6d输出：
```
header: 
  seq: 147
  stamp: 
    secs: 1637046891
    nsecs: 727083247
  frame_id: ''
id: 4000221
self_drone_id: 4
remote_drone_id: 1031
relative_pose: 
  pose: 
    position: 
      x: -1.10917544365
      y: 0.653852045536
      z: 0.0347665697336
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.00223105029448
      w: 0.999997511204
  covariance: [0.08053945749998093, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.04263318330049515, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.005435848608613014, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.18665659427642822, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.18665659427642822, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.18665659427642822]
is_2d_detect: False
is_yaw_valid: True
probaility: 0.0
local_pose_self: 
  position: 
    x: 0.0
    y: 0.0
    z: 0.0
  orientation: 
    x: 0.0
    y: 0.0
    z: 0.0
    w: 0.0
local_pose_remote: 
  position: 
    x: 0.0
    y: 0.0
    z: 0.0
  orientation: 
    x: 0.0
    y: 0.0
    z: 0.0
    w: 0.0
dof_4: False
```

3. rqt_graph:
<img width="1763" alt="rosgraph" src="https://github.com/user-attachments/assets/f8cb7760-4674-4f13-a13c-b4dbb311c8a8" />
